apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
      app: nginx     
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30065
    protocol: TCP
  selector:
       app: nginx
